services:    
  db-miami:
    image: mariadb:latest
    container_name: db-miami
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    networks:
      - beach-network
    volumes:
      - db_data:/var/lib/mysql
#Containers de wordpress, um e dois. (usados para balancear carga primariamente)
  wordpress-miami:
    image: wordpress:latest
    container_name: wordpress-miami
    depends_on:
      - db-miami
    restart: always
    tty: true
    environment:
      WORDPRESS_DB_HOST: db-miami
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wordpress
    networks:
      - beach-network
      - proxy-praia
    volumes:
      - wordpress_data:/var/www/html
      - ./containers/WORDPRESS/wp-config.php:/var/www/html/wp-config.php
  wordpress-2-miami:
    image: wordpress:latest
    container_name: wordpress-2-miami
    depends_on:
      - db-miami
    restart: always
    tty: true
    environment:
      WORDPRESS_DB_HOST: db-miami
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wordpress
    networks:
      - beach-network
      - proxy-praia
    volumes:
      - wordpress_data:/var/www/html
      - ./containers/WORDPRESS/wp-config.php:/var/www/html/wp-config.php
  ssh:
    build:
      context: ./Containers/SSH
      dockerfile: Dockerfile
    image: ssh
    container_name: ssh-miami
    ports:
      - "2223:22"
    networks:
      - beach-network

  proxy-miami:
    build:
      context: ./Containers/PROXY
      dockerfile: Dockerfile
    image: proxy
    container_name: proxy-miami
    depends_on:
      - wordpress-miami
      - wordpress-2-miami
    networks:
      - beach-network
      - proxy-praia
    dns:
      - 192.168.0.3 # Adiciona o servidor DNS
    volumes:
      - ./Containers/PROXY/Config/default.conf:/etc/nginx/conf.d/default.conf
      - ./Containers/PROXY/Config/nginx.conf:/etc/nginx/nginx.conf
      - ./Containers/PROXY/Config/ssl:/etc/nginx/ssl

volumes:
  db_data:
  wordpress_data:

#Redes {lembre-se sempre de criar a rede proxy praia com docker network create proxy-praia}
networks:
  beach-network:
    driver: bridge
  proxy-praia:
    external: true