services:    
  db:
    image: mariadb:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    networks:
      - beach-network
    volumes:
      - db_data:/var/lib/mysql
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    hostname: wordpress
    domainname: redinha.com
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wordpress
    networks:
      - beach-network
    volumes:
      - wordpress_data:/var/www/html
  proxy:
    build:
      context: ./Containers/PROXY
      dockerfile: dockerfile
    image: proxy_redinha
    container_name: proxy_redinha
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - beach-network
    depends_on:
      - wordpress
    volumes:
      - ./Containers/PROXY/Config/default.conf:/etc/nginx/conf.d/default.conf
      - ./Containers/PROXY/Config/nginx.conf:/etc/nginx/nginx.conf
      - ./Containers/PROXY/Config/ssl:/etc/nginx/ssl
    dns:
      - 10.0.2.15  # Endereço IP do servidor DNS do provedor
volumes:
  db_data:
  wordpress_data:

networks:
  beach-network:
    driver: bridge
