services:    
  db:
    image: mariadb:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    networks:
      - redinha-network
    volumes:
      - db_data:/var/lib/mysql
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    hostname: wordpress
    domainname: redinha.com
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wordpress
    networks:
      - proxy-praia
      - redinha-network
    volumes:
      - wordpress_data:/var/www/html

volumes:
  db_data:
  wordpress_data:

networks:
  redinha-network:
    driver: bridge
  proxy-praia:
    driver: true